# Generated by Django for analytics app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('risk_score', models.FloatField(blank=True, default=0.0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_visitor_profiles',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=64)),
                ('os', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('referrer', models.URLField(blank=True, max_length=512)),
                ('landing_page', models.CharField(blank=True, max_length=512)),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('page_views_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitorprofile')),
            ],
            options={
                'db_table': 'analytics_visitor_sessions',
                'ordering': ['-entry_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('referrer', models.CharField(blank=True, max_length=512)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitorsession')),
            ],
            options={
                'db_table': 'analytics_page_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('element_id', models.CharField(blank=True, max_length=128)),
                ('element_class', models.CharField(blank=True, max_length=256)),
                ('target_url', models.CharField(blank=True, max_length=512)),
                ('page_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='analytics.visitorsession')),
            ],
            options={
                'db_table': 'analytics_click_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('register_success', 'Register Success'), ('register_failed', 'Register Failed'), ('logout', 'Logout'), ('password_reset_request', 'Password Reset Request'), ('password_reset_success', 'Password Reset Success')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email_attempted', models.EmailField(blank=True, max_length=254)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_events', to='analytics.visitorsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_auth_events', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_events', to='analytics.visitorprofile')),
            ],
            options={
                'db_table': 'analytics_auth_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('registered_visitors', models.PositiveIntegerField(default=0)),
                ('guest_visitors', models.PositiveIntegerField(default=0)),
                ('new_registrations', models.PositiveIntegerField(default=0)),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('top_pages', models.JSONField(blank=True, default=dict)),
                ('top_countries', models.JSONField(blank=True, default=dict)),
                ('top_browsers', models.JSONField(blank=True, default=dict)),
                ('top_devices', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_daily_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_by_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_admin_notes', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_records', to='analytics.visitorprofile')),
            ],
            options={
                'db_table': 'analytics_admin_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=16)),
                ('sent_to', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('date_range', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_report_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('risk_assessment', models.TextField(blank=True)),
                ('behavior_notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_ai_analyses', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='analytics.visitorprofile')),
            ],
            options={
                'db_table': 'analytics_ai_analysis_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
