# Generated by Django 5.2.4 on 2026-03-08 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('risk_assessment', models.TextField(blank=True)),
                ('behavior_notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_ai_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_ai_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('registered_visitors', models.PositiveIntegerField(default=0)),
                ('guest_visitors', models.PositiveIntegerField(default=0)),
                ('new_registrations', models.PositiveIntegerField(default=0)),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('top_pages', models.JSONField(blank=True, default=dict)),
                ('top_countries', models.JSONField(blank=True, default=dict)),
                ('top_browsers', models.JSONField(blank=True, default=dict)),
                ('top_devices', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Daily Traffic',
                'db_table': 'analytics_daily_traffic',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_security_profile',
            },
        ),
        migrations.CreateModel(
            name='WeeklyTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, unique=True)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('new_registrations', models.PositiveIntegerField(default=0)),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('top_pages', models.JSONField(blank=True, default=dict)),
                ('top_countries', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_weekly_traffic',
                'ordering': ['-week_start'],
            },
        ),
        migrations.RemoveField(
            model_name='aianalysisrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aianalysisrecord',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='DailyTrafficSnapshot',
        ),
        migrations.RemoveField(
            model_name='visitorprofile',
            name='notes',
        ),
        migrations.AddField(
            model_name='visitorprofile',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitorprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='analytics.visitorprofile'),
        ),
        migrations.DeleteModel(
            name='AIAnalysisRecord',
        ),
    ]
