# Generated by Django 5.2.4 on 2026-03-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_aianalysisresult_dailytraffic_usersecurityprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='footprint_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Data sent to AI'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='0-100 from AI', null=True),
        ),
    ]
